-- MySQL Script generated by MySQL Workbench
-- Fri Sep  1 07:33:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Roomies
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Roomies
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Roomies` DEFAULT CHARACTER SET utf8 ;
USE `Roomies` ;

-- -----------------------------------------------------
-- Table `Roomies`.`busqueda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Roomies`.`busqueda` (
  `ID_busqueda` INT NOT NULL,
  `criterios` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_busqueda`))
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `Roomies`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Roomies`.`usuarios` (
  `ID_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `edad` INT NOT NULL,
  `ocupacion` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `estilo-de-vida` VARCHAR(300) NOT NULL,
  `busqueda_ID_busqueda` INT NOT NULL,
  `tipo` INT NOT NULL,
  PRIMARY KEY (`ID_usuario`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  INDEX `fk_usuarios_busqueda_idx` (`busqueda_ID_busqueda` ASC),
  CONSTRAINT `fk_usuarios_busqueda`
    FOREIGN KEY (`busqueda_ID_busqueda`)
    REFERENCES `Roomies`.`busqueda` (`ID_busqueda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Roomies`.`propiedades`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Roomies`.`propiedades` (
  `ID_propiedades` INT NOT NULL,
  `ubicacion` VARCHAR(45) NULL,
  `precio` INT NULL,
  `tipo_de_propiedad` CHAR(45) NULL,
  `Caracteristicas` VARCHAR(100) NULL,
  PRIMARY KEY (`ID_propiedades`)
)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `Roomies`.`comentario`
-- -----------------------------------------------------
-- ...

CREATE TABLE IF NOT EXISTS `Roomies`.`comentario` (
  `ID-comentario` INT NOT NULL AUTO_INCREMENT,
  `contenido` VARCHAR(100) NULL,
  `calificacion` INT NULL,
  `id-usuario` INT NOT NULL,
  `id-propiedad` INT NULL,
  PRIMARY KEY (`ID-comentario`),
  INDEX `id-usuario_idx` (`id-usuario` ASC),
  INDEX `id-propiedad_idx` (`id-propiedad` ASC),
  CONSTRAINT `fk_comentario_usuario`
    FOREIGN KEY (`id-usuario`)
    REFERENCES `Roomies`.`usuarios` (`ID_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentario_propiedad`
    FOREIGN KEY (`id-propiedad`)
    REFERENCES `Roomies`.`propiedades` (`ID_propiedades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Roomies`.`reglas`
-- -----------------------------------------------------
INSERT INTO `Roomies`.`usuarios` (`nombre`, `correo`, `edad`, `ocupacion`, `contraseña`, `estilo-de-vida`, `busqueda_ID_busqueda`, `tipo`)
VALUES
    ('Juan', 'juan@email.com', 25, 'Estudiante', 'clave123', 'Activo', 1, 1),
    ('Ana', 'ana@email.com', 30, 'Profesional', 'clave456', 'Activo', 2, 2),
    ('Carlos', 'carlos@email.com', 28, 'Profesional', 'clave789', 'Activo', 3, 2),
    ('Laura', 'laura@email.com', 24, 'Estudiante', 'clave101', 'Activo', 4, 1),
    ('Miguel', 'miguel@email.com', 35, 'Profesional', 'clave202', 'Activo', 5, 2),
	('María', 'maria@email.com', 29, 'Profesional', 'clave303', 'Activo', 6, 2),
    ('Pedro', 'pedro@email.com', 27, 'Estudiante', 'clave404', 'Activo', 7, 1),
    ('Luis', 'luis@email.com', 32, 'Profesional', 'clave505', 'Activo', 8, 2),
    ('Sofía', 'sofia@email.com', 26, 'Estudiante', 'clave606', 'Activo', 9, 1),
    ('Elena', 'elena@email.com', 34, 'Profesional', 'clave707', 'Activo', 10, 2);

INSERT INTO `Roomies`.`propiedades` (`ubicacion`, `precio`, `tipo_de_propiedad`, `Caracteristicas`)
VALUES
    ('Ciudad A', 1000, 'Casa', '3 habitaciones, 2 baños'),
    ('Ciudad B', 800, 'Apartamento', '2 habitaciones, 1 baño'),
    ('Ciudad C', 1200, 'Casa', '4 habitaciones, 3 baños'),
    ('Ciudad D', 900, 'Apartamento', '1 habitación, 1 baño'),
    ('Ciudad E', 1500, 'Casa', '5 habitaciones, 4 baños'),
    ('Ciudad F', 1100, 'Casa', '4 habitaciones, 3 baños'),
    ('Ciudad G', 950, 'Apartamento', '2 habitaciones, 2 baños'),
    ('Ciudad H', 1300, 'Casa', '5 habitaciones, 4 baños'),
    ('Ciudad I', 1050, 'Apartamento', '1 habitación, 1 baño'),
    ('Ciudad J', 1400, 'Casa', '6 habitaciones, 5 baños');

-- Inserción de 10 registros en la tabla 'busqueda'
INSERT INTO `Roomies`.`busqueda` (`criterios`)
VALUES
    ('Ciudad A, Casa, 3 habitaciones'),
    ('Ciudad B, Apartamento, 2 habitaciones'),
    ('Ciudad C, Casa, 4 habitaciones'),
    ('Ciudad D, Apartamento, 1 habitación'),
    ('Ciudad E, Casa, 5 habitaciones'),
    ('Ciudad F, Apartamento, 2 habitaciones'),
    ('Ciudad G, Casa, 4 habitaciones'),
    ('Ciudad H, Apartamento, 1 habitación'),
    ('Ciudad I, Casa, 6 habitaciones'),
    ('Ciudad J, Apartamento, 3 habitaciones');

INSERT INTO `Roomies`.`comentario` (`contenido`, `calificacion`, `id-usuario`, `id-propiedad`)
VALUES
    ('Buena ubicación, cerca del transporte público.', 4, 1, 1),
    ('Excelente vista desde el balcón.', 5, 2, 3),
    ('Amplio espacio y jardín trasero.', 4, 3, 2),
    ('El vecindario es tranquilo y seguro.', 5, 4, 4),
    ('Buen precio para un apartamento de 1 habitación.', 4, 5, 5),
    ('Muy recomendado para familias.', 5, 1, 6),
    ('Cerca de tiendas y restaurantes.', 4, 2, 7),
    ('Bonita casa con piscina.', 5, 3, 8),
    ('Buena relación calidad-precio.', 4, 4, 9),
    ('El propietario es amable y atento.', 5, 5, 10);






SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
